# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-31 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLenguajeProcesador',
            fields=[
                ('id_lenguajeprocesador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('version', models.IntegerField()),
                ('componente_binario', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=15)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_lenguaje_procesador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminOrigendatos',
            fields=[
                ('id_origendatos', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_conexion', models.CharField(max_length=10)),
                ('url_jdbc', models.CharField(blank=True, max_length=200, null=True)),
                ('usuario_jdbc', models.CharField(blank=True, max_length=30, null=True)),
                ('clave_jdbc', models.CharField(blank=True, max_length=30, null=True)),
                ('nombre_jndi', models.CharField(blank=True, max_length=30, null=True)),
                ('hora_sistema', models.CharField(blank=True, max_length=30, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_origendatos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminProyectoAlcance',
            fields=[
                ('id_alcance', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'admin_proyecto_alcance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoArchivos',
            fields=[
                ('id_archivo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=150, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('upload', models.FileField(upload_to='user_templates')),
            ],
            options={
                'db_table': 'genco_archivos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoComponentes',
            fields=[
                ('id_componente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_componentes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoConversionTipodato',
            fields=[
                ('id_conversion', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_conversion_tipodato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoDirectorioElementos',
            fields=[
                ('id_direlemento', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'genco_directorio_elementos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoDirectorios',
            fields=[
                ('id_directorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_directorios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoEntidad',
            fields=[
                ('id_entidad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoEntidadDefinicion',
            fields=[
                ('id_entidaddef', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('longitud', models.IntegerField(blank=True, null=True)),
                ('precision', models.IntegerField(blank=True, null=True)),
                ('es_pk', models.CharField(blank=True, max_length=10, null=True)),
                ('es_fk', models.CharField(blank=True, max_length=10, null=True)),
                ('obligatorio', models.CharField(blank=True, max_length=10, null=True)),
                ('regexpr', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_entidad_definicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoEntorno',
            fields=[
                ('id_entorno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('icono', models.CharField(blank=True, max_length=50, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_entorno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoEntornoLenguajes',
            fields=[
                ('id_entornolenguaje', models.AutoField(primary_key=True, serialize=False)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'genco_entorno_lenguajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoGrupo',
            fields=[
                ('id_grupo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_grupo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoLenguajes',
            fields=[
                ('id_lenguaje', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_lenguajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoParametros',
            fields=[
                ('id_parametro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('valor_numerico', models.IntegerField(blank=True, null=True)),
                ('valor_alfanumerico', models.CharField(blank=True, max_length=200, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_parametros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoPlantillaEntidad',
            fields=[
                ('id_plantillaentidad', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.CharField(max_length=1024)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'genco_plantilla_entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoPlantillas',
            fields=[
                ('id_plantilla', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('upload', models.FileField(upload_to='user_templates')),
                ('tags', models.CharField(max_length=512)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_plantillas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoProyectoRepositorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'genco_proyecto_repositorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoProyectos',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('grupo', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_archivo_constructor', models.CharField(blank=True, max_length=100, null=True)),
                ('empaquetado', models.CharField(blank=True, max_length=45, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('version', models.CharField(max_length=45)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_proyectos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoRepositorio',
            fields=[
                ('id_repositorio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('url_ext_repositorio', models.CharField(blank=True, max_length=300, null=True)),
                ('token_ext_repositorio', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'genco_repositorio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoTipodato',
            fields=[
                ('id_tipodato', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('contenedor', models.CharField(blank=True, max_length=100, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=10, null=True)),
                ('longitud_maxima', models.IntegerField(blank=True, null=True)),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
                ('modificado_por', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genco_tipodato',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GencoUsuarioGrupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.IntegerField()),
                ('creado_por', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'genco_usuario_grupo',
                'managed': False,
            },
        ),
    ]
